# need to add server.  entries to enable HTTPS with SSL keystore, replace "????" with correct entries

server.port=8443
server.ssl.key-alias=artemis
server.ssl.key-store-password=JY3miGNA7rpCkmVgk6iLdQ
server.ssl.key-store=classpath:artemis_keystore.p12
server.ssl.key-store-type=PKCS12

